spring.application.name=blog-app-apis

spring.datasource.url=jdbc:mysql://localhost:3306/blog_app_apis
spring.datasource.username=cmss
spring.datasource.password=Cmss@123


spring.jpa.hibernate.ddl-auto=update